sudo: false
cache: pip
language: python
python: 3.6
env:
  matrix:
  - TOX_ENV=apidocs
install:
- pip install tox
script: tox -e $TOX_ENV
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_API_KEY"
  keep-history: true
  on:
    branch: sphinx
