sudo: false
cache: pip
language: python
python: 3.6

env:
    - TOX_ENV=apidocs

install:
    - pip install tox

script:
    tox -e $TOX_ENV

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_API_TOKEN
    keep-history: true
    on:
        branch: master

